packages:
  - "auth"
  - "security"
  - "lib/*"
  - "middleware"
  - "types"
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
